doctrine:
    dbal:
        # configure these for your database server
        url: '%env(resolve:DATABASE_URL)%'
        dbname: project3_db
        host: localhost
        port: 3306
        user: root
        password: null
        driver: mysql